menu/urls.py
from django.urls import path
from menu.views import *

app_name = 'menu'

urlpatterns = [
    path('<int:menu_id>/', view_menu, name='view_menu'),
]

up_trader_test/urls.py
from django.contrib import admin
from django.urls import path, include
from menu import urls as menu_urls
from menu.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('menu/', include(menu_urls, namespace='menu')),
]

menu/models.py
from django.db import models


class Menu(models.Model):
    title = models.CharField(max_length=100, verbose_name='Название меню')
    parent = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, verbose_name='Родитель')

    def __str__(self):
        return self.title

    def get_elder_ids(self):
        if self.parent:
            return self.parent.get_elder_ids() + [self.parent.id]
        else:
            return []

    def children(self):
        return self.menu_set.all()

menu/forms.py
from django import forms

menu/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'menu/index.html')


def view_menu(request, menu_id):
    return render(request, 'menu/index.html')

menu/templates/menu/draw_menu.html
{% load draw_menu %}
<details {% if menu.id in opened_menu_ids %} open {% endif %}>
    <summary> <a href="{% url 'menu:view_menu' menu.id %}">{{ menu.title }}</a> </summary>
    <ul>
        {% for child in menu.children %}
            {% draw_menu_children child.id %}
        {% endfor %}
    </ul>
</details>

menu/templates/menu/index.html
{% load draw_menu %}

<html lang="en">
  <style>
       html {padding: 30px}
       p {
        margin-left: 3em;
       }
  </style>
<head>
    <meta charset="UTF-8">
    <title>Menu</title>
</head>
<body>
    {% draw_menu 'main_menu' %}
    {% draw_menu 'second_menu' %}
    {% draw_menu 'third_menu' %}
</body>
</html>